source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/fsh/fast-syntax-highlighting.plugin.zsh
source ~/.config/zsh/plugins/zsh-nvm/zsh-nvm.plugin.zsh
source ~/.config/zsh/plugins/jump.sh
source ~/.config/zsh/plugins/jump.sh
source ~/.config/zsh/plugins/starship.sh
source ~/.config/zsh/plugins/fzf.sh
source ~/.config/zsh/plugins/fzf-fn.sh
source ~/.config/zsh/plugins/base16.sh
source ~/.config/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
