allow_remote_control yes
include ./gruvbox_light_med.conf

font_family JetBrains Mono 
font_size 14
macos_thicken_font 0.27
adjust_line_height 125%
cursor_blink_interval 0
window_padding_width 10
hide_window_decorations titlebar-only
remember_window_size  yes
enable_audio_bell no
term xterm-kitty
